/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "login": [],
    "login.store": [],
    "logout": [],
    "password.request": [],
    "password.reset": [
        {
            "name": "token",
            "required": true
        }
    ],
    "password.email": [],
    "password.update": [],
    "register": [],
    "register.store": [],
    "verification.notice": [],
    "verification.verify": [
        {
            "name": "id",
            "required": true
        },
        {
            "name": "hash",
            "required": true
        }
    ],
    "verification.send": [],
    "password.confirm": [],
    "password.confirmation": [],
    "password.confirm.store": [],
    "verification.code": [],
    "home": [],
    "media.store": [
        {
            "name": "modelType",
            "required": true
        },
        {
            "name": "modelId",
            "required": true
        },
        {
            "name": "collection",
            "required": true
        }
    ],
    "settings.index": [],
    "settings.profile.edit": [],
    "settings.profile.update": [],
    "settings.profile.destroy": [],
    "settings.security.edit": [],
    "settings.password.update": [],
    "settings.appearance.edit": [],
    "storage.local": [
        {
            "name": "path",
            "required": true
        }
    ]
}
}
export {};
